services:
  weaviate:
    image: semitechnologies/weaviate:1.24.10
    restart: always
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'

      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://t2v:8080'

      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'weaviate-admin'
      AUTHENTICATION_APIKEY_USERS: 'admin'

      AUTHORIZATION_ENABLED: 'true'
      ENABLE_MODULES: 'text2vec-transformers'
      LIMIT_MAX_RESULTS: 200

    volumes:
      - weaviate_data:/var/lib/weaviate

  t2v:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    restart: always
    ports:
      - "8081:8080"
    environment:
      TRANSFORMERS_INFERENCE_NUM_THREADS: 4

volumes:
  weaviate_data:
